name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: supurazako/github-actions-hands-on@main
      - run: cat README.md
